# A demo CRD for the Kopf example operators.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webapps.dev.io
spec:
  scope: Namespaced
  group: dev.io
  names:
    kind: webapps
    plural: webapps
    singular: webapp
    shortNames:
      - web
  versions:
    - name: v1
      served: true
      storage: true
      subresources: { status: { } }  
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      