apiVersion: apps/v1
kind: Deployment
metadata:
    name: webapp-operator
spec:
    selector:
        matchLabels:
            app: webapp-operator
    template:
        metadata:
            labels:
                app: webapp-operator
        spec:
            serviceAccountName: webapp-operator
            containers:
                - image: adityank003/operator-webapp
                  name: webapp-operator
  
